dbt_operator_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USER', 'postgres') }}"
      password: "{{ env_var('DBT_PASSWORD', '') }}"
      port: "{{ env_var('DBT_PORT', 5432) }}"
      dbname: "{{ env_var('DBT_DATABASE', 'postgres') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'public') }}"
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      retry_on_database_error: true
      
    prod:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USER', 'postgres') }}"
      password: "{{ env_var('DBT_PASSWORD', '') }}"
      port: "{{ env_var('DBT_PORT', 5432) }}"
      dbname: "{{ env_var('DBT_DATABASE', 'postgres') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'public') }}"
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      retry_on_database_error: true

