name: Quick Build

on:
  workflow_dispatch:
    inputs:
      operator:
        description: 'dbt-operator to build'
        required: true
        default: 'dbt-operator'
        type: choice
        options:
          - dbt
          - dbt-core-operator
          - dbt-postgres-operator
      image_tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
        type: string

env:
  REGISTRY_URL: 'localhost:65000'
  IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}
  OPERATOR_NAME: ${{ github.event.inputs.operator || 'dbt' }}

jobs:
  quick-build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and test
      run: |
        cd ${{ env.OPERATOR_NAME }}
        echo "Building ${{ env.OPERATOR_NAME }}:${{ env.IMAGE_TAG }}"
        make build IMAGE_NAME=${{ env.OPERATOR_NAME }} IMAGE_TAG=${{ env.IMAGE_TAG }} REGISTRY=${{ env.REGISTRY_URL }}
        make test IMAGE_NAME=${{ env.OPERATOR_NAME }} IMAGE_TAG=${{ env.IMAGE_TAG }} REGISTRY=${{ env.REGISTRY_URL }}

    - name: Show image info
      run: |
        cd ${{ env.OPERATOR_NAME }}
        make size IMAGE_NAME=${{ env.OPERATOR_NAME }} IMAGE_TAG=${{ env.IMAGE_TAG }} REGISTRY=${{ env.REGISTRY_URL }}
